package com.palmap.exhibition.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACTIVITY_MODEL.
 */
public class ActivityModel {

    private Long id;
    private int atyId;
    private int mapId;
    private int buildId;
    private int floorId;
    private int poiId;
    /** Not-null value. */
    private String activityType;
    /** Not-null value. */
    private String startTime;
    /** Not-null value. */
    private String endTime;
    /** Not-null value. */
    private String activityName;
    /** Not-null value. */
    private String activityDesc;
    /** Not-null value. */
    private String roomNumber;
    /** Not-null value. */
    private String ext;
    private int state;
    private Integer aimsCount;

    public ActivityModel() {
    }

    public ActivityModel(Long id) {
        this.id = id;
    }

    public ActivityModel(Long id, int atyId, int mapId, int buildId, int floorId, int poiId, String activityType, String startTime, String endTime, String activityName, String activityDesc, String roomNumber, String ext, int state, Integer aimsCount) {
        this.id = id;
        this.atyId = atyId;
        this.mapId = mapId;
        this.buildId = buildId;
        this.floorId = floorId;
        this.poiId = poiId;
        this.activityType = activityType;
        this.startTime = startTime;
        this.endTime = endTime;
        this.activityName = activityName;
        this.activityDesc = activityDesc;
        this.roomNumber = roomNumber;
        this.ext = ext;
        this.state = state;
        this.aimsCount = aimsCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getAtyId() {
        return atyId;
    }

    public void setAtyId(int atyId) {
        this.atyId = atyId;
    }

    public int getMapId() {
        return mapId;
    }

    public void setMapId(int mapId) {
        this.mapId = mapId;
    }

    public int getBuildId() {
        return buildId;
    }

    public void setBuildId(int buildId) {
        this.buildId = buildId;
    }

    public int getFloorId() {
        return floorId;
    }

    public void setFloorId(int floorId) {
        this.floorId = floorId;
    }

    public int getPoiId() {
        return poiId;
    }

    public void setPoiId(int poiId) {
        this.poiId = poiId;
    }

    /** Not-null value. */
    public String getActivityType() {
        return activityType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }

    /** Not-null value. */
    public String getStartTime() {
        return startTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /** Not-null value. */
    public String getEndTime() {
        return endTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /** Not-null value. */
    public String getActivityName() {
        return activityName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /** Not-null value. */
    public String getActivityDesc() {
        return activityDesc;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setActivityDesc(String activityDesc) {
        this.activityDesc = activityDesc;
    }

    /** Not-null value. */
    public String getRoomNumber() {
        return roomNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    /** Not-null value. */
    public String getExt() {
        return ext;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setExt(String ext) {
        this.ext = ext;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public Integer getAimsCount() {
        return aimsCount;
    }

    public void setAimsCount(Integer aimsCount) {
        this.aimsCount = aimsCount;
    }

}
