package com.palmap.exhibition.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COORDINATE_MODEL.
 */
public class CoordinateModel {

    private Long id;
    private double x;
    private double y;
    private double z;
    /** Not-null value. */
    private String pointId;
    /** Not-null value. */
    private String atyId;

    public CoordinateModel() {
    }

    public CoordinateModel(Long id) {
        this.id = id;
    }

    public CoordinateModel(Long id, double x, double y, double z, String pointId, String atyId) {
        this.id = id;
        this.x = x;
        this.y = y;
        this.z = z;
        this.pointId = pointId;
        this.atyId = atyId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getX() {
        return x;
    }

    public void setX(double x) {
        this.x = x;
    }

    public double getY() {
        return y;
    }

    public void setY(double y) {
        this.y = y;
    }

    public double getZ() {
        return z;
    }

    public void setZ(double z) {
        this.z = z;
    }

    /** Not-null value. */
    public String getPointId() {
        return pointId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPointId(String pointId) {
        this.pointId = pointId;
    }

    /** Not-null value. */
    public String getAtyId() {
        return atyId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAtyId(String atyId) {
        this.atyId = atyId;
    }

}
