package com.palmap.exhibition.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HISTORY_POI_SEARCH.
 */
public class HistoryPoiSearch {

    private Long id;
    /** Not-null value. */
    private String poiKeyWord;
    /** Not-null value. */
    private String appKey;

    public HistoryPoiSearch() {
    }

    public HistoryPoiSearch(Long id) {
        this.id = id;
    }

    public HistoryPoiSearch(Long id, String poiKeyWord, String appKey) {
        this.id = id;
        this.poiKeyWord = poiKeyWord;
        this.appKey = appKey;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPoiKeyWord() {
        return poiKeyWord;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPoiKeyWord(String poiKeyWord) {
        this.poiKeyWord = poiKeyWord;
    }

    /** Not-null value. */
    public String getAppKey() {
        return appKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

}
