package com.palmap.exhibition.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.palmap.exhibition.dao.HistoryPoiSearch;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HISTORY_POI_SEARCH.
*/
public class HistoryPoiSearchDao extends AbstractDao<HistoryPoiSearch, Long> {

    public static final String TABLENAME = "HISTORY_POI_SEARCH";

    /**
     * Properties of entity HistoryPoiSearch.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PoiKeyWord = new Property(1, String.class, "poiKeyWord", false, "POI_KEY_WORD");
        public final static Property AppKey = new Property(2, String.class, "appKey", false, "APP_KEY");
    };


    public HistoryPoiSearchDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryPoiSearchDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HISTORY_POI_SEARCH' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'POI_KEY_WORD' TEXT NOT NULL ," + // 1: poiKeyWord
                "'APP_KEY' TEXT NOT NULL );"); // 2: appKey
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HISTORY_POI_SEARCH'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HistoryPoiSearch entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPoiKeyWord());
        stmt.bindString(3, entity.getAppKey());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HistoryPoiSearch readEntity(Cursor cursor, int offset) {
        HistoryPoiSearch entity = new HistoryPoiSearch( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // poiKeyWord
            cursor.getString(offset + 2) // appKey
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HistoryPoiSearch entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPoiKeyWord(cursor.getString(offset + 1));
        entity.setAppKey(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(HistoryPoiSearch entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(HistoryPoiSearch entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
